- name: Download python
  get_url: 
    url: "https://www.python.org/ftp/python/{{ item.release }}/Python-{{ item.release }}.tar.xz"
    dest: "{{ working_dir }}"
  with_items:
    - "{{ python_versions }}"

- name: Expand python archive archive.
  unarchive: 
    src: "{{ working_dir }}/Python-{{ item.release }}.tar.xz"
    dest: "{{ working_dir }}"
    creates: "{{ working_dir }}/Python-{{ item.release }}"
    copy: False
  with_items:
    - "{{ python_versions }}"

- name: Build python
  shell: "cd {{ working_dir }}/Python-{{ item.release }}  && ./configure --prefix={{ install_dir }} && make altinstall"
  with_items:
    - "{{ python_versions }}"

